version: '3.7'
services:
  server:
    build: ./server
    working_dir: /server
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    tty: true
    command:
      ["./backend_api/manage.py", "runserver", "0.0.0.0:8000"]

  redis:
    image: redis
    ports:
      - "6379:6379"

  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==<yourmasternode>"
    volumes:
      - ./clusters:/spark-jobs
  spark-worker:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
